"""Re-sync the mod's copies of vanilla files with the installed CK3 version.

Three mod files are copies of vanilla files with Coptic changes on top:
  - common/landed_titles/coptic_title.txt  (vanilla k_egypt nested in its empire, plus Coptic cultural names)
  - history/provinces/k_egypt.txt          (vanilla file, with some counties set to culture = coptic)
  - history/cultures/coptic.txt            (vanilla history/cultures/egyptian.txt)

The Coptic changes are read from the current mod files, so the mod files stay the source of truth:
add a cultural name or a Coptic county in the mod file, then run this script after each game patch.

Usage:
  python tools/sync_vanilla.py            rebuild the files from the installed game
  python tools/sync_vanilla.py --check    only report what would change (exit code 1 if anything would)
  python tools/sync_vanilla.py --deploy   also copy the mod to the local CK3 mod folder for testing
  --game PATH                             CK3 "game" folder (default: $CK3_GAME_DIR or the Steam default)
"""
import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

MOD = Path(__file__).resolve().parent.parent
DEFAULT_GAME = Path(r"C:/Program Files (x86)/Steam/steamapps/common/Crusader Kings III/game")
DEPLOY_DIR = Path.home() / "Documents/Paradox Interactive/Crusader Kings III/mod/Coptic Culture"
DEPLOY_ITEMS = ["common", "history", "localization", "descriptor.mod", "thumbnail.png"]

TITLES = "common/landed_titles/coptic_title.txt"
PROVINCES = "history/provinces/k_egypt.txt"
CULTURE_HISTORY = "history/cultures/coptic.txt"
KINGDOM = "k_egypt"

TITLES_PREAMBLE = """@correct_culture_primary_score = 100
@better_than_the_alternatives_score = 50
@always_primary_score = 1000
@never_primary_score = -1000

# Generated by tools/sync_vanilla.py from CK3 {version} common/landed_titles/00_landed_titles.txt:
# vanilla {kingdom} and the properties of its empire {empire}, with Coptic cultural names added.
# {kingdom} MUST stay nested in {empire}: a title redefined at the top level of a later
# file loses its de jure liege, which removed Egypt from the Arabian Empire.
# Only the {empire} properties are copied here; its other kingdoms are untouched.
"""

COPTIC_AI_PRIORITY = [
    "\t\t\tif = {",
    "\t\t\t\tlimit = {",
    "\t\t\t\t\tculture = culture:coptic",
    "\t\t\t\t}",
    "\t\t\t\tadd = @correct_culture_primary_score",
    "\t\t\t}",
]


class SyncError(Exception):
    pass


def read_text(path):
    raw = path.read_bytes()
    return raw.decode("utf-8-sig").replace("\r\n", "\n"), raw.startswith(b"\xef\xbb\xbf"), b"\r\n" in raw


def encode(text, bom, crlf):
    if crlf:
        text = text.replace("\n", "\r\n")
    return (b"\xef\xbb\xbf" if bom else b"") + text.encode("utf-8")


def game_version(game):
    settings = game.parent / "launcher/launcher-settings.json"
    try:
        return json.loads(settings.read_text(encoding="utf-8"))["rawVersion"]
    except (OSError, KeyError, ValueError):
        return "unknown version"


def block_end(lines, start, indent):
    for i in range(start + 1, len(lines)):
        if lines[i] == indent + "}":
            return i
    raise SyncError(f"unterminated block at line {start + 1}")


def build_titles(game, version):
    """Vanilla empire properties + vanilla k_egypt, with the mod's cultural names re-injected."""
    mod_text, _, _ = read_text(MOD / TITLES)
    names = {}
    # A title, then any lines that are not another title definition, then its cultural_names block
    title_names = r"\n\t+([bcdk]_[\w-]+) = \{\n(?:(?!\t+[bcdk]_[\w-]+ = \{)[^\n]*\n)*?\t+cultural_names = \{\n\t+name_list_coptic = (\w+)"
    for m in re.finditer(title_names, mod_text):
        names[m.group(1)] = m.group(2)
    if not names:
        raise SyncError(f"no Coptic cultural names found in {TITLES}")

    vanilla, _, _ = read_text(game / "common/landed_titles/00_landed_titles.txt")
    lines = vanilla.split("\n")
    k_start = next((i for i, l in enumerate(lines) if l == f"\t{KINGDOM} = {{"), None)
    if k_start is None:
        raise SyncError(f"{KINGDOM} is no longer nested directly in an empire in vanilla; update this script")
    e_start = max(i for i in range(k_start) if re.match(r"^[eh]_\w+ = \{", lines[i]))
    empire = lines[e_start].split(" ")[0]
    first_child = next(i for i in range(e_start + 1, len(lines)) if re.match(r"^\t[kdc]_[\w-]+ = \{", lines[i]))
    header = lines[e_start:first_child]
    while header and not header[-1].strip():
        header.pop()
    kingdom = lines[k_start:block_end(lines, k_start, "\t") + 1]

    out, pending, done = [], None, set()
    for line in kingdom:
        m = re.match(r"^(\t+)([bcdk]_[\w-]+) = \{", line)
        if m and m.group(2) in names:
            pending = (m.group(1), m.group(2))
        out.append(line)
        if pending:
            indent, key = pending
            anchor = r"^\t+province = \d+" if key.startswith("b_") else r"^\t+color = \{"
            if re.match(anchor, line) and line.startswith(indent + "\t"):
                out += ["", f"{indent}\tcultural_names = {{", f"{indent}\t\tname_list_coptic = {names[key]}", f"{indent}\t}}"]
                done.add(key)
                pending = None
        if line == "\t\tai_primary_priority = {" and "ai" not in done:
            out += COPTIC_AI_PRIORITY
            done.add("ai")
    missing = sorted(set(names) - done)
    if missing:
        raise SyncError(f"titles with Coptic names not found in vanilla {KINGDOM}: {', '.join(missing)}")
    if "ai" not in done:
        raise SyncError(f"vanilla {KINGDOM} has no ai_primary_priority block; update this script")

    preamble = TITLES_PREAMBLE.format(version=version, kingdom=KINGDOM, empire=empire)
    return preamble + "\n" + "\n".join(header) + "\n\n" + "\n".join(out) + "\n}\n"


def build_provinces(game, version):
    """Vanilla province history with the mod's Coptic provinces set to culture = coptic."""
    mod_text, _, _ = read_text(MOD / PROVINCES)
    coptic = re.findall(r"(?m)^(\d+) = \{[^\n]*\n\tculture = coptic\b", mod_text)
    if not coptic:
        raise SyncError(f"no 'culture = coptic' provinces found in {PROVINCES}")

    vanilla, _, _ = read_text(game / "history/provinces/k_egypt.txt")
    text = vanilla
    for pid in coptic:
        pattern = re.compile(rf"(?m)^({pid} = \{{[^\n]*\n\tculture = )\w+")
        text, n = pattern.subn(r"\1coptic", text)
        if n != 1:
            raise SyncError(f"province {pid} has no leading 'culture =' line in vanilla {PROVINCES}")
    header = (
        f"# Generated by tools/sync_vanilla.py: full override of vanilla history/provinces/k_egypt.txt (CK3 {version}).\n"
        f"# The only change from vanilla is 'culture = coptic' on provinces {', '.join(coptic)}.\n"
        f"# To add a Coptic county, set its culture here, then re-run the script after each game patch.\n"
    )
    return header + text


def build_culture_history(game, version):
    vanilla, _, _ = read_text(game / "history/cultures/egyptian.txt")
    return vanilla


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--game", type=Path, default=Path(os.environ.get("CK3_GAME_DIR", DEFAULT_GAME)))
    parser.add_argument("--check", action="store_true", help="report changes without writing (exit 1 if any)")
    parser.add_argument("--deploy", action="store_true", help=f"also copy the mod to {DEPLOY_DIR}")
    args = parser.parse_args()

    if not (args.game / "common/landed_titles/00_landed_titles.txt").is_file():
        sys.exit(f"CK3 game folder not found: {args.game} (use --game or CK3_GAME_DIR)")
    version = game_version(args.game)
    print(f"CK3 {version} at {args.game}")

    changed = []
    try:
        for rel, build in ((TITLES, build_titles), (PROVINCES, build_provinces), (CULTURE_HISTORY, build_culture_history)):
            path = MOD / rel
            _, bom, crlf = read_text(path)
            new = encode(build(args.game, version), bom, crlf)
            if new != path.read_bytes():
                changed.append(rel)
                if not args.check:
                    path.write_bytes(new)
    except SyncError as e:
        sys.exit(f"ERROR: {e}")

    verb = "would change" if args.check else "updated"
    print(f"{verb}: {', '.join(changed)}" if changed else "already in sync with vanilla")

    descriptor, _, _ = read_text(MOD / "descriptor.mod")
    supported = re.search(r'supported_version="([\d.]+)', descriptor)
    if supported and not version.startswith(supported.group(1).rstrip(".")):
        print(f'NOTE: descriptors say supported_version="{supported.group(1)}*" but the game is {version}; '
              "update both descriptor.mod and Coptic Culture.mod")

    if args.deploy and not args.check:
        DEPLOY_DIR.mkdir(parents=True, exist_ok=True)
        for item in DEPLOY_ITEMS:
            src, dst = MOD / item, DEPLOY_DIR / item
            if src.is_dir():
                shutil.rmtree(dst, ignore_errors=True)
                shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)
        print(f"deployed to {DEPLOY_DIR}")

    if args.check and changed:
        sys.exit(1)


if __name__ == "__main__":
    main()
